

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_script: 
  - cd react-frontend 
  - npm install
  
script:
  - npm test

before_deploy: cd ..

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "eu-west-1"  
  app: "WePick3"
  env: "WePickFinal"
  bucket_name: "elasticbeanstalk-eu-west-1-855059450301"
  on:
  branch: master

  