branch-defaults:
  Eddie:
    environment: WePickFinal
    group_suffix: null
global:
  application_name: WePick3
  branch: null
  default_ec2_keyname: WePickFlaskApp
  default_platform: Python 3.6
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
